### ISSUE TITLE
Unable to import xslx

### ISSUE THREAD

**Issue by stuarthalloway** [cgrand/spreadmap#2]
This time I tried exporting from Google Drive spreadsheet to XSLX.  When I try to access a cell, I get 

```
IllegalArgumentException Unexpected workbook type (org.apache.poi.xssf.usermodel.XSSFWorkbook)
    org.apache.poi.ss.formula.eval.forked.ForkedEvaluator.createEvaluationWorkbook (ForkedEvaluator.java:63)
    org.apache.poi.ss.formula.eval.forked.ForkedEvaluator.create (ForkedEvaluator.java:75)
    net.cgrand.spreadmap/getter/fn--873 (spreadmap.clj:46)
```

**Comment by cgrand** [comment]
Indeed :-(

So a quick glance at source http://svn.apache.org/repos/asf/poi/trunk/src/java/org/apache/poi/ss/formula/eval/forked/ForkedEvaluator.java makes the reason seems to be a dependency issue between poi and poi-ooxml.

None of the classes in org/apache/poi/ss/formula/eval/forked seem complex so either forking them out of POI or reimplementing them in Clojure may solve the problem.

**Comment by stuarthalloway** [comment]
Awesome, verified the fix here.
